spring:
  application:
    name: ${APP_NAME:api}
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:100MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:100MB}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5001/app}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:changeme}
  cloud:
    aws:
      s3:
        endpoint: ${AWS_S3_ENDPOINT:http://s3.localhost.localstack.cloud:4566}
        region: ${AWS_REGION:us-east-1}
        path-style-access-enabled: true
      credentials:
        access-key: ${AWS_ACCESS_KEY:localstack}
        secret-key: ${AWS_SECRET_KEY:localstack}
      region:
        static: ${AWS_REGION_STATIC:us-east-1}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  mvc:
    pathmatch:
      matching-strategy: ${MVC_PATHMATCH_STRATEGY:ant_path_matcher}
  jackson:
    serialization:
      fail-on-empty-beans: ${JACKSON_FAIL_ON_EMPTY_BEANS:false}
  flyway:
    enabled: false
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: ${API_DOCS_PATH:/api-docs}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}

app:
  s3:
    default-bucket-name: ${S3_DEFAULT_BUCKET_NAME:spang}
  admin-user:
    enabled: ${ADMIN_USER_ENABLED:false}
    username: ${ADMIN_USER_USERNAME:admin}
    password: ${ADMIN_USER_PASSWORD:changeme}
  security:
    access-token:
      expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME:86400000}
      secret: ${ACCESS_TOKEN_SECRET:changeme}
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID:}
        client-secret: ${GOOGLE_CLIENT_SECRET:}
        redirect-uri: ${GOOGLE_REDIRECT_URI:}
        enabled: ${GOOGLE_OAUTH_ENABLED:false}
  password:
    strength: ${PASSWORD_STRENGTH:10}

