BEGIN;

ALTER TABLE assignments
ADD COLUMN IF NOT EXISTS keep_answers_ordered BOOLEAN DEFAULT FALSE;

COMMIT;

BEGIN;

ALTER TABLE questions
ADD COLUMN IF NOT EXISTS assignment_order INTEGER DEFAULT 0;

COMMIT;
